import { and, asc, eq } from 'drizzle-orm'
import { db } from '@/db'
import { conversations, messages } from '@/db/schema'
import { parseJson, uuidSchema } from '@/lib/api'
import { requireUser } from '@/lib/auth'

export const runtime = 'nodejs'
const bodySchema = z.object({ title: z.string().trim().min(1).max(200).optional() })
const paramsSchema = z.object({ id: uuidSchema })
async function owned(id: string, userId: string) { return db.select().from(conversations).where(and(eq(conversations.id, id), eq(conversations.userId, userId))).limit(1) }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const p = parseJson(paramsSchema, await params); if (!p.ok) return p.response; const [row] = await owned(p.data.id, user.id); return row ? Response.json({ conversation: row }) : Response.json({ error: 'Not found' }, { status: 404 }) } catch { return Response.json({ error: 'Unauthorized' }, { status: 401 }) } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const p = parseJson(paramsSchema, await params); if (!p.ok) return p.response; const b = parseJson(bodySchema, await request.json().catch(() => null)); if (!b.ok) return b.response; const [current] = await owned(p.data.id, user.id); if (!current) return Response.json({ error: 'Not found' }, { status: 404 }); let title = b.data.title; if (title && current.title !== 'New conversation') { const [firstUser] = await db.select({ content: messages.contentText }).from(messages).where(and(eq(messages.conversationId, p.data.id), eq(messages.role, 'user'))).orderBy(asc(messages.createdAt)).limit(1); const autoCandidate = firstUser?.content.slice(0, 48).trim(); if (autoCandidate && title === autoCandidate) title = undefined }
  const [row] = await db.update(conversations).set({ ...(title !== undefined ? { title } : {}), updatedAt: new Date() }).where(and(eq(conversations.id, p.data.id), eq(conversations.userId, user.id))).returning(); return row ? Response.json({ conversation: row }) : Response.json({ error: 'Not found' }, { status: 404 }) } catch { return Response.json({ error: 'Unauthorized' }, { status: 401 }) } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const p = parseJson(paramsSchema, await params); if (!p.ok) return p.response; const result = await db.delete(conversations).where(and(eq(conversations.id, p.data.id), eq(conversations.userId, user.id))).returning({ id: conversations.id }); return result.length ? Response.json({ ok: true }) : Response.json({ error: 'Not found' }, { status: 404 }) } catch { return Response.json({ error: 'Unauthorized' }, { status: 401 }) } }
