'use client'

import { FormEvent, useState } from 'react'
import { ArrowLeft, ArrowRight, Eye, EyeOff, Loader2, Mail } from 'lucide-react'
import { useRouter } from 'next/navigation'

export default function AuthPage(){
  const router=useRouter()
  const [mode,setMode]=useState<'signin'|'signup'>('signin')
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('')
  const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function submit(e?:FormEvent){e?.preventDefault();setError('');setBusy(true);try{const endpoint=mode==='signin'?'/api/auth/login':'/api/auth/signup';const body=mode==='signin'?{email,password}:{displayName:name,email,password};const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'Unable to continue. Please try again.');router.replace('/');router.refresh()}catch(err){setError(err instanceof Error?err.message:'Unable to continue.')}finally{setBusy(false)}}
  return <main className="auth-page">
    <header className="auth-top"><button onClick={()=>router.back()} aria-label="Go back"><ArrowLeft size={20}/></button><span>Clue</span><div/></header>
    <section className="auth-shell">
      <div className="auth-mark">C</div><h1>{mode==='signin'?'Welcome back.':'Create your Clue account.'}</h1><p className="lead">{mode==='signin'?'Sign in to continue your conversations and generated files.':'A simple account keeps your conversations and generated files with you.'}</p>
      <div className="auth-tabs"><button className={mode==='signin'?'active':''} onClick={()=>{setMode('signin');setError('')}}>Sign in</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('')}}>Create account</button></div>
      <form onSubmit={submit}>
        {mode==='signup'&&<label><span>Name</span><input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/></label>}
        <label><span>Email</span><div className="field"><Mail size={17}/><input type="email" inputMode="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></div></label>
        <label><span>Password</span><div className="field"><input type={show?'text':'password'} autoComplete={mode==='signin'?'current-password':'new-password'} minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" required/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
        {error&&<div className="auth-error">{error}</div>}
        <button className="submit" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<>{mode==='signin'?'Continue':'Create account'}<ArrowRight size={18}/></>}</button>
      </form>
      <div className="auth-divider"><span>Private by default</span></div><p className="fine">By continuing, you agree to Clue&apos;s Terms and Privacy Policy.</p>
    </section>
    <style jsx>{`*{box-sizing:border-box}.auth-page{min-height:100dvh;background:#f7f7f5;color:#171719;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.auth-top{height:64px;display:grid;grid-template-columns:44px 1fr 44px;align-items:center;padding:0 16px}.auth-top button{width:38px;height:38px;border:0;border-radius:12px;background:transparent;display:grid;place-items:center;color:#444;cursor:pointer}.auth-top button:hover{background:#ecece8}.auth-top span{text-align:center;font-family:Georgia,"Times New Roman",serif;font-size:21px;font-style:italic;letter-spacing:-.04em}.auth-shell{width:min(430px,calc(100% - 32px));margin:0 auto;padding:54px 0 40px}.auth-mark{width:44px;height:44px;border-radius:14px;background:#171719;color:#fff;display:grid;place-items:center;font-family:Georgia,serif;font-size:21px;font-style:italic;margin-bottom:22px}.auth-shell h1{font-family:Georgia,"Times New Roman",serif;font-weight:400;font-size:36px;line-height:1.08;letter-spacing:-.045em;margin:0}.lead{color:#7d7d83;font-size:13px;line-height:1.65;margin:12px 0 26px}.auth-tabs{display:grid;grid-template-columns:1fr 1fr;background:#e9e9e5;padding:4px;border-radius:13px;margin-bottom:22px}.auth-tabs button{border:0;background:transparent;border-radius:10px;padding:10px 8px;color:#77777d;font-size:12px;font-weight:650;cursor:pointer}.auth-tabs button.active{background:#fff;color:#171719;box-shadow:0 1px 4px rgba(0,0,0,.08)}form{display:grid;gap:14px}label{display:grid;gap:7px}label>span{font-size:11px;font-weight:650;color:#55555b}.field,input{width:100%;height:52px;border:1px solid #deded9;border-radius:14px;background:#fff;color:#171719}.field{display:flex;align-items:center;gap:9px;padding:0 14px}.field>svg{color:#999;flex:none}.field input{height:100%;border:0;border-radius:0;outline:0;padding:0;background:transparent}.field button{border:0;background:transparent;color:#8c8c92;display:grid;place-items:center;padding:5px;cursor:pointer}.field:focus-within,input:focus{border-color:#9f9fa3;box-shadow:0 0 0 4px rgba(23,23,25,.05);outline:0}.auth-error{padding:10px 12px;border-radius:11px;background:#fff1ef;color:#9a4036;font-size:12px;line-height:1.5}.submit{height:52px;border:0;border-radius:14px;background:#171719;color:#fff;display:flex;align-items:center;justify-content:center;gap:8px;font-size:13px;font-weight:650;cursor:pointer}.submit:disabled{opacity:.6;cursor:default}.spin{animation:spin .8s linear infinite}.auth-divider{display:flex;align-items:center;gap:12px;margin:28px 0 10px;color:#aaa;font-size:10px}.auth-divider:before,.auth-divider:after{content:'';height:1px;background:#e2e2dd;flex:1}.auth-divider span{white-space:nowrap}.fine{text-align:center;color:#aaa;font-size:10px;line-height:1.6;margin:0}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:520px){.auth-shell{padding-top:42px}.auth-shell h1{font-size:32px}}`}</style>
  </main>
}
